---
title: "Spillningsinventering björn, Västerbottens län 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

Detta bibliotek innehåller programkod och data som använts för populationsberäkningar av björn, baserat på spillningsinventeringen i Västerbottens län 2019. Koden är skriven i R och anropar programmet [MARK](http://www.phidot.org/software/mark/) genom gränssnittet RMark.

```{r}
library(tidyverse)
library(RMark) 
source("functions.R")

data2019 <- read_csv("Bjorn_AC_2019_spillning_0616.csv") %>% 
  rename(Datum = Funnetdato) %>% 
  mutate(Vecka = lubridate::isoweek(Datum)) %>% 
  arrange(Datum) %>% 
  mutate(Kon = ifelse(is.na(Kon), "Saknas", Kon))

fit2019 <- data2019 %>% 
  filter(Kon != "Saknas") %>% 
  fit_models()

fit2019 %>% 
  select(Modell = model, dAICc, Hanar,  Honor, Total) %>% 
  knitr::kable(caption = "Populationsskattningar för undersökta modeller baserat på inventeringen i Västerbottens län 2019. 
               Modellerna är rangordnade efter Akaikes informationskriterium med den högst rankade modellen överst.")
```

